### ISSUE TITLE
cross platform

### ISSUE THREAD

**Issue by steveoh** [terrajobst/dotnet-nuget-gc#1]
ran this on osx and... :boom:
```cs
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/me\.nuget\packages\'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories()
   at NugetCacheCleaner.Program.Main(String[] args) in /home/vsts/work/1/s/src/Program.cs:line 15
```

**Comment by terrajobst** [comment]
Ah yes 😄

**Comment by terrajobst** [comment]
Fixed by #3.

**Comment by steveoh** [comment]
ding this issue when you cut/push a new release and i'll test it.

**Comment by terrajobst** [comment]
0.1.12 is pushed. However, it will take approximately 5 - 10 minutes before NuGet has indexed it.

```
dotnet tool update dotnet-nuget-gc -g
```

***Update**: It's now live.*

**Comment by steveoh** [comment]
worked great. thanks! ✨
